/**
 * Tapping a chip fills search with the same text as the label and runs the catalog query.
 */
export const STAPLE_SEARCH_SUGGESTIONS = [
  'Roti',
  'Chapati',
  'Bhakri',
  'Varan Dal',
  'Amti',
  'Rice',
  'Poha',
  'Upma',
  'Sabudana Khichdi',
  'Sabudana Vada',
  'Misal Pav',
  'Pav Bhaji',
  'Usal',
  'Zunka',
  'Pithla',
  'Thecha',
  'Batata Bhaji',
  'Kanda Bhaji',
  'Thalipeeth',
  'Dhokla',
  'Idli',
  'Dosa',
  'Sambar',
  'Curd',
  'Buttermilk',
  'Ghee',
  'Pickle',
  'Papad',
  'Sheera',
  'Shrikhand',
  'Modak',
  'Ladoo',
  'Khichdi',
  'Masala Rice',
  'Vegetable Pulao',
  'Paneer Bhurji',
  'Egg Bhurji',
  'Chicken Curry',
  'Mutton Curry',
  'Fish Curry',
] as const;

export type StapleSearchLabel = (typeof STAPLE_SEARCH_SUGGESTIONS)[number];
